data:
  batch_size: 4
  data_path: processed_ETH_USDT_data.feather
  num_workers: 0
  prediction_length: 5
  sequence_length: 50
  train_ratio: 0.8
distributed:
  num_workers: 1
  use_distributed: false
model:
  d_model: 256
  dropout: 0.1
  input_dim: 4
  nhead: 8
  num_decoder_layers: 4
  num_encoder_layers: 4
  prediction_length: 5
  sequence_length: 50
optimizer:
  betas:
  - 0.9
  - 0.999
  lr: 0.0001
  scheduler: plateau
  weight_decay: 0.01
resume_from_checkpoint: null
save_dir: checkpoints
training:
  epochs: 100
