data:
  batch_size: 32
  data_path: processed_ETH_USDT_data.feather
  num_workers: 0
  prediction_length: 5
  sequence_length: 100
  train_ratio: 0.8
distributed:
  num_workers: 1
  use_distributed: false
model:
  d_model: 768
  dropout: 0.1
  input_dim: 4
  nhead: 12
  num_decoder_layers: 6
  num_encoder_layers: 6
  prediction_length: 5
  sequence_length: 100
  use_flash_attention: true          # 新增：启用Flash Attention
optimizer:
  betas:
  - 0.9
  - 0.999
  lr: 0.0001
  scheduler: plateau
  weight_decay: 0.01
resume_from_checkpoint: null
save_dir: checkpoints
training:
  epochs: 50