data:
  batch_size: 128
  data_path: OHLCVD_ETH_USDT_data_1m.feather
  num_workers: 4
  prediction_length: 10
  sequence_length: 150
  train_ratio: 0.8

distributed:
  use_distributed: false
  num_workers: 2
  backend: nccl

model:
  d_model: 768
  dropout: 0.1
  input_dim: 6 # 等于特征列的数量
  nhead: 12
  num_decoder_layers: 6
  num_encoder_layers: 6
  prediction_length: 10
  sequence_length: 150
  use_flash_attention: false          # 等待修补
  use_xformers: false                 # 等待修补
  feature_columns: ['open', 'high', 'low', 'close', 'volume', 'delta']  # 新增：特征列

optimizer:
  betas: [0.9, 0.999]
  lr: 0.0002
  scheduler: plateau
  weight_decay: 0.01

training:
  epochs: 50
  mixed_precision: true

resume_from_checkpoint: null
save_dir: checkpoints_2gpu