data:
  data_path: 'processed_ETH_USDT_data.feather'
  batch_size: 64  # 总batch size，会被分到各个worker
  sequence_length: 100
  prediction_length: 5
  train_ratio: 0.8
  num_workers: 2

model:
  input_dim: 4
  sequence_length: 100
  prediction_length: 5
  d_model: 512
  num_encoder_layers: 6
  num_decoder_layers: 6
  nhead: 8
  dropout: 0.1
  use_flash_attention: false

optimizer:
  lr: 0.0001  # Ray会自动根据worker数量调整学习率
  weight_decay: 0.01
  betas: [0.9, 0.999]
  scheduler: 'plateau'

training:
  epochs: 50
  mixed_precision: false

distributed:
  use_distributed: true
  num_workers: 2  # 使用2个GPU worker

save_dir: 'ray_checkpoints'
resume_from_checkpoint: null